version: "2"
services:
  teradata:
    build:
      context: .
    ports:
      - "8888:8888"
    command: /usr/local/bin/start-notebook.sh --NotebookApp.token='' --NotebookApp.ip='*' --debug
    volumes:
      - ./Makefile:/home/nbuser/work/Makefile:ro
      - ./teradata_test_connect.py:/home/nbuser/work/teradata_test_connect.py:ro
