version: "2"
services:
  teradata:
    build:
      context: .
    volumes:
      - ./Makefile:/home/nbuser/work/Makefile:ro
      - ./teradata_test_connect.py:/home/nbuser/work/teradata_test_connect.py:ro
